#!/bin/bash
# Generate .env file for Maestro E2E tests
set -e

cat > .env <<EOF
NORDVPN_USERNAME=${NORDVPN_USERNAME}
NORDVPN_PASSWORD=${NORDVPN_PASSWORD}
TEST_VPN_HOSTNAME=${TEST_VPN_HOSTNAME}
TEST_VPN_REGION=${TEST_VPN_REGION}
TEST_APP_PACKAGE=${TEST_APP_PACKAGE}
EOF
