package com.multiregionvpn.data.database

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents a user-configured VPN server.
 * Can be either a manually configured server or a JIT-generated config.
 */
@Entity(tableName = "vpn_configs")
data class VpnConfig(
    @PrimaryKey
    val id: String, // e.g., "uuid-12345"
    val name: String, // e.g., "My Nord UK Server"
    val regionId: String, // e.g., "UK"
    val templateId: String, // e.g., "nordvpn"
    val serverHostname: String, // e.g., "uk1860.nordvpn.com"
    // JIT VPN fields:
    val sourceProviderId: String? = null, // Provider ID if this was generated by a provider
    val generatedAt: Long? = null // Timestamp when this config was generated (for cache invalidation)
)

